global using static battlesdk.types.TypesExt;
using docgen;
using System.CommandLine;

var xmldocOption = new Option<string>("--xmldoc") { Required = true };
var outOption = new Option<string>("--out", "-o");

var cmd = new RootCommand("BattleSDK's documentation generator.") {
    xmldocOption,
    outOption
};

cmd.SetAction(res => {
    string xmlDocPath = res.GetValue(xmldocOption) ?? throw new(
        "XmlDoc must be provided. This document can be generated by BattleSDK."
    );

    string outputDir = res.GetValue(outOption) ?? Environment.CurrentDirectory;


    Console.WriteLine("Generating Lua API documentation.");

    LuaDocGenerator gen = new(xmlDocPath);
    gen.GenerateTypesFile(outputDir);
});

var res = cmd.Parse(args);
return res.Invoke();